spring.application.name=practical-assessment
spring.datasource.url=jdbc:mysql://localhost:3306/assessment_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=724145017
spring.jpa.hibernate.ddl-auto=update
